//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Name="Webservices Generico ZeusSoap", Namespace="http://www.w3.org/XML/1998/namespace:lang", ConfigurationName="ServiceReference1.WebservicesGenericoZeusSoap")]
    public interface WebservicesGenericoZeusSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.w3.org/XML/1998/namespace:lang/SessionIDToken", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.SoapResponse> SessionIDTokenAsync(ServiceReference1.SoapRequest Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.w3.org/XML/1998/namespace:lang/ClosedSessionIDToken", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.SoapResponse> ClosedSessionIDTokenAsync(ServiceReference1.SoapRequest Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.w3.org/XML/1998/namespace:lang/StandardCommunicationSOAP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.SoapResponse> StandardCommunicationSOAPAsync(ServiceReference1.SoapRequest Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.w3.org/XML/1998/namespace:lang/EmailValidate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.SoapResponse> EmailValidateAsync(ServiceReference1.SoapRequest Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.w3.org/XML/1998/namespace:lang/ExecuteActionSOAP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.SoapResponse> ExecuteActionSOAPAsync(ServiceReference1.SoapRequestAction Request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/XML/1998/namespace:lang")]
    public partial class SoapRequest
    {
        
        private string typeSQLField;
        
        private string dynamicPropertyField;
        
        private string sessionIDField;
        
        private string actionField;
        
        private string bodyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string TypeSQL
        {
            get
            {
                return this.typeSQLField;
            }
            set
            {
                this.typeSQLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DynamicProperty
        {
            get
            {
                return this.dynamicPropertyField;
            }
            set
            {
                this.dynamicPropertyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string SessionID
        {
            get
            {
                return this.sessionIDField;
            }
            set
            {
                this.sessionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Action
        {
            get
            {
                return this.actionField;
            }
            set
            {
                this.actionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Body
        {
            get
            {
                return this.bodyField;
            }
            set
            {
                this.bodyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/XML/1998/namespace:lang")]
    public partial class SoapRequestAction
    {
        
        private string typeSQLField;
        
        private string dynamicPropertyField;
        
        private string userField;
        
        private string passwordField;
        
        private string actionField;
        
        private string bodyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string TypeSQL
        {
            get
            {
                return this.typeSQLField;
            }
            set
            {
                this.typeSQLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DynamicProperty
        {
            get
            {
                return this.dynamicPropertyField;
            }
            set
            {
                this.dynamicPropertyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string User
        {
            get
            {
                return this.userField;
            }
            set
            {
                this.userField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Action
        {
            get
            {
                return this.actionField;
            }
            set
            {
                this.actionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Body
        {
            get
            {
                return this.bodyField;
            }
            set
            {
                this.bodyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/XML/1998/namespace:lang")]
    public partial class SoapResponse
    {
        
        private string sessionIDField;
        
        private string bodyField;
        
        private Status statusField;
        
        private string messageField;
        
        private string codeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SessionID
        {
            get
            {
                return this.sessionIDField;
            }
            set
            {
                this.sessionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Body
        {
            get
            {
                return this.bodyField;
            }
            set
            {
                this.bodyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Status Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/XML/1998/namespace:lang")]
    public enum Status
    {
        
        /// <remarks/>
        SUCCESS,
        
        /// <remarks/>
        FAILD,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface WebservicesGenericoZeusSoapChannel : ServiceReference1.WebservicesGenericoZeusSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class WebservicesGenericoZeusSoapClient : System.ServiceModel.ClientBase<ServiceReference1.WebservicesGenericoZeusSoap>, ServiceReference1.WebservicesGenericoZeusSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WebservicesGenericoZeusSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(WebservicesGenericoZeusSoapClient.GetBindingForEndpoint(endpointConfiguration), WebservicesGenericoZeusSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebservicesGenericoZeusSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WebservicesGenericoZeusSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebservicesGenericoZeusSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WebservicesGenericoZeusSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebservicesGenericoZeusSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.SoapResponse> SessionIDTokenAsync(ServiceReference1.SoapRequest Request)
        {
            return base.Channel.SessionIDTokenAsync(Request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.SoapResponse> ClosedSessionIDTokenAsync(ServiceReference1.SoapRequest Request)
        {
            return base.Channel.ClosedSessionIDTokenAsync(Request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.SoapResponse> StandardCommunicationSOAPAsync(ServiceReference1.SoapRequest Request)
        {
            return base.Channel.StandardCommunicationSOAPAsync(Request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.SoapResponse> EmailValidateAsync(ServiceReference1.SoapRequest Request)
        {
            return base.Channel.EmailValidateAsync(Request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.SoapResponse> ExecuteActionSOAPAsync(ServiceReference1.SoapRequestAction Request)
        {
            return base.Channel.ExecuteActionSOAPAsync(Request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Webservices_x0020_Generico_x0020_ZeusSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.Webservices_x0020_Generico_x0020_ZeusSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Webservices_x0020_Generico_x0020_ZeusSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.0.85/wsGenericoZeus/ServiceWS.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.Webservices_x0020_Generico_x0020_ZeusSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.0.85/wsGenericoZeus/ServiceWS.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            Webservices_x0020_Generico_x0020_ZeusSoap,
            
            Webservices_x0020_Generico_x0020_ZeusSoap12,
        }
    }
}
